### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by fikedev** [luispedro/diskhash#6]
C:\Users\user1>pip install diskhash
Collecting diskhash
  Using cached https://files.pythonhosted.org/packages/1e/a4/672ea698c480c44025dd6f82ea2fe1482814d18cc33f0ddac97f8972b860/diskhash-0.4.0.tar.gz
Building wheels for collected packages: diskhash
  Building wheel for diskhash (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\user1\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user1\\AppData\\Local\\Temp\\pip-install-n8q6wuhq\\diskhash\\setup.py'"'"'; __file__='"'"'C:\\Users\\user1\\AppData\\Local\\Temp\\pip-install-n8q6wuhq\\diskhash\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\user1\AppData\Local\Temp\pip-wheel-g297yx0g' --python-tag cp37
       cwd: C:\Users\user1\AppData\Local\Temp\pip-install-n8q6wuhq\diskhash\
  Complete output (25 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.7
  creating build\lib.win32-3.7\diskhash
  copying python\diskhash\diskhash_version.py -> build\lib.win32-3.7\diskhash
  copying python\diskhash\__init__.py -> build\lib.win32-3.7\diskhash
  creating build\lib.win32-3.7\diskhash\tests
  copying python\diskhash\tests\test_larger.py -> build\lib.win32-3.7\diskhash\tests
  copying python\diskhash\tests\test_smoke.py -> build\lib.win32-3.7\diskhash\tests
  copying python\diskhash\tests\__init__.py -> build\lib.win32-3.7\diskhash\tests
  running build_ext
  building 'diskhash._diskhash' extension
  creating build\temp.win32-3.7
  creating build\temp.win32-3.7\Release
  creating build\temp.win32-3.7\Release\python
  creating build\temp.win32-3.7\Release\python\diskhash
  creating build\temp.win32-3.7\Release\src
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\user1\appdata\local\programs\python\python37-32\include -Ic:\users\user1\appdata\local\programs\python\python37-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\winrt" /Tcpython/diskhash/_diskhash.c /Fobuild\temp.win32-3.7\Release\python/diskhash/_diskhash.obj
  _diskhash.c
  python/diskhash/_diskhash.c(121): error C2078: too many initializers
  python/diskhash/_diskhash.c(117): error C2078: too many initializers
  python/diskhash/_diskhash.c(196): warning C4028: formal parameter 1 different from declaration
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for diskhash
  Running setup.py clean for diskhash
Failed to build diskhash
Installing collected packages: diskhash
    Running setup.py install for diskhash ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\user1\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user1\\AppData\\Local\\Temp\\pip-install-n8q6wuhq\\diskhash\\setup.py'"'"'; __file__='"'"'C:\\Users\\user1\\AppData\\Local\\Temp\\pip-install-n8q6wuhq\\diskhash\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\user1\AppData\Local\Temp\pip-record-nrcm6gyo\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\user1\AppData\Local\Temp\pip-install-n8q6wuhq\diskhash\
    Complete output (25 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.7
    creating build\lib.win32-3.7\diskhash
    copying python\diskhash\diskhash_version.py -> build\lib.win32-3.7\diskhash
    copying python\diskhash\__init__.py -> build\lib.win32-3.7\diskhash
    creating build\lib.win32-3.7\diskhash\tests
    copying python\diskhash\tests\test_larger.py -> build\lib.win32-3.7\diskhash\tests
    copying python\diskhash\tests\test_smoke.py -> build\lib.win32-3.7\diskhash\tests
    copying python\diskhash\tests\__init__.py -> build\lib.win32-3.7\diskhash\tests
    running build_ext
    building 'diskhash._diskhash' extension
    creating build\temp.win32-3.7
    creating build\temp.win32-3.7\Release
    creating build\temp.win32-3.7\Release\python
    creating build\temp.win32-3.7\Release\python\diskhash
    creating build\temp.win32-3.7\Release\src
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\user1\appdata\local\programs\python\python37-32\include -Ic:\users\user1\appdata\local\programs\python\python37-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\winrt" /Tcpython/diskhash/_diskhash.c /Fobuild\temp.win32-3.7\Release\python/diskhash/_diskhash.obj
    _diskhash.c
    python/diskhash/_diskhash.c(121): error C2078: too many initializers
    python/diskhash/_diskhash.c(117): error C2078: too many initializers
    python/diskhash/_diskhash.c(196): warning C4028: formal parameter 1 different from declaration
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\user1\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user1\\AppData\\Local\\Temp\\pip-install-n8q6wuhq\\diskhash\\setup.py'"'"'; __file__='"'"'C:\\Users\\user1\\AppData\\Local\\Temp\\pip-install-n8q6wuhq\\diskhash\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\user1\AppData\Local\Temp\pip-record-nrcm6gyo\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

C:\Users\user1>

**Comment by luispedro** [comment]
Thanks for the report. The new release on pypi should work now

**Comment by fikedev** [comment]
*Dear Luis,*

*    I am fekadu from Ethiopia. before a day I have reported issue related
with installation of diskhash. And I saw the commit you did as new version
release. I have try to install again using pip install diskhash command on
command prompt. I use windows 10 pro. But, still same problem encountered.
If there is some conflict with other IDE like visual studio, *please* let
me know. you can see the whole installation error log i posted last time
for the details.*

*The other thing I want ask you about the diskhash that Is it possible too
use the diskhash library to use secondary memory as a primary memory to
store hash tables and also to make it directly communicate with cpu so that
to decrease memory overhead for some data mining algorithms during run
time?*

*I am doing my thesis work on big data mining algorithms and I want to use
secondary memory to store my hash table. I hope I hear from you soon.*

*with best regards*

*fekadu*

**Comment by luispedro** [comment]
Are you sure you have tried installing the new version? I cannot directly test on Windows, but I the errors you saw were warnings on gcc and they are gone.

**Comment by fikedev** [comment]
Yes I have tried and still the same problem I got. Is it problem if the version of python installed is more than the one you mentioned?
======================here is the log file/ error =====================
Microsoft Windows [Version 10.0.17134.950]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>pip install diskhash
Collecting diskhash
  Using cached https://files.pythonhosted.org/packages/38/fc/d3ecd8c9dd3d51a9af1e0139c2a962cb621e933468a152f131e272ddddd1/diskhash-0.4.1.tar.gz
Building wheels for collected packages: diskhash
  Building wheel for diskhash (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\user1\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user1\\AppData\\Local\\Temp\\pip-install-ec295znr\\diskhash\\setup.py'"'"'; __file__='"'"'C:\\Users\\user1\\AppData\\Local\\Temp\\pip-install-ec295znr\\diskhash\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\user1\AppData\Local\Temp\pip-wheel-kzvnb8xa' --python-tag cp37
       cwd: C:\Users\user1\AppData\Local\Temp\pip-install-ec295znr\diskhash\
  Complete output (26 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.7
  creating build\lib.win32-3.7\diskhash
  copying python\diskhash\diskhash_version.py -> build\lib.win32-3.7\diskhash
  copying python\diskhash\str2int_tool.py -> build\lib.win32-3.7\diskhash
  copying python\diskhash\__init__.py -> build\lib.win32-3.7\diskhash
  creating build\lib.win32-3.7\diskhash\tests
  copying python\diskhash\tests\test_larger.py -> build\lib.win32-3.7\diskhash\tests
  copying python\diskhash\tests\test_smoke.py -> build\lib.win32-3.7\diskhash\tests
  copying python\diskhash\tests\__init__.py -> build\lib.win32-3.7\diskhash\tests
  running build_ext
  building 'diskhash._diskhash' extension
  creating build\temp.win32-3.7
  creating build\temp.win32-3.7\Release
  creating build\temp.win32-3.7\Release\python
  creating build\temp.win32-3.7\Release\python\diskhash
  creating build\temp.win32-3.7\Release\src
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\user1\appdata\local\programs\python\python37-32\include -Ic:\users\user1\appdata\local\programs\python\python37-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\winrt" /Tcpython/diskhash/_diskhash.c /Fobuild\temp.win32-3.7\Release\python/diskhash/_diskhash.obj
  _diskhash.c
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\user1\appdata\local\programs\python\python37-32\include -Ic:\users\user1\appdata\local\programs\python\python37-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\winrt" /Tcsrc/diskhash.c /Fobuild\temp.win32-3.7\Release\src/diskhash.obj
  diskhash.c
  src/diskhash.c(8): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for diskhash
  Running setup.py clean for diskhash
Failed to build diskhash
Installing collected packages: diskhash
    Running setup.py install for diskhash ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\user1\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user1\\AppData\\Local\\Temp\\pip-install-ec295znr\\diskhash\\setup.py'"'"'; __file__='"'"'C:\\Users\\user1\\AppData\\Local\\Temp\\pip-install-ec295znr\\diskhash\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\user1\AppData\Local\Temp\pip-record-l3rqcolt\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\user1\AppData\Local\Temp\pip-install-ec295znr\diskhash\
    Complete output (26 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.7
    creating build\lib.win32-3.7\diskhash
    copying python\diskhash\diskhash_version.py -> build\lib.win32-3.7\diskhash
    copying python\diskhash\str2int_tool.py -> build\lib.win32-3.7\diskhash
    copying python\diskhash\__init__.py -> build\lib.win32-3.7\diskhash
    creating build\lib.win32-3.7\diskhash\tests
    copying python\diskhash\tests\test_larger.py -> build\lib.win32-3.7\diskhash\tests
    copying python\diskhash\tests\test_smoke.py -> build\lib.win32-3.7\diskhash\tests
    copying python\diskhash\tests\__init__.py -> build\lib.win32-3.7\diskhash\tests
    running build_ext
    building 'diskhash._diskhash' extension
    creating build\temp.win32-3.7
    creating build\temp.win32-3.7\Release
    creating build\temp.win32-3.7\Release\python
    creating build\temp.win32-3.7\Release\python\diskhash
    creating build\temp.win32-3.7\Release\src
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\user1\appdata\local\programs\python\python37-32\include -Ic:\users\user1\appdata\local\programs\python\python37-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\winrt" /Tcpython/diskhash/_diskhash.c /Fobuild\temp.win32-3.7\Release\python/diskhash/_diskhash.obj
    _diskhash.c
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\user1\appdata\local\programs\python\python37-32\include -Ic:\users\user1\appdata\local\programs\python\python37-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\winrt" /Tcsrc/diskhash.c /Fobuild\temp.win32-3.7\Release\src/diskhash.obj
    diskhash.c
    src/diskhash.c(8): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\user1\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user1\\AppData\\Local\\Temp\\pip-install-ec295znr\\diskhash\\setup.py'"'"'; __file__='"'"'C:\\Users\\user1\\AppData\\Local\\Temp\\pip-install-ec295znr\\diskhash\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\user1\AppData\Local\Temp\pip-record-l3rqcolt\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

C:\WINDOWS\system32>

**Comment by luispedro** [comment]
Ah, this is a new error. You need `unistd.h`, which I guess is probably supported on Windows if you install some compatibility layer, but that's all beyond what I can do.
